project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - columns.qmd
    - rows.qmd
    - groups.qmd
execute: 
  cache: false
website:
  title: "dataframes"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2026, Bigelow Laboratory for Ocean Science" 
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: Subsetting columns (variables)
        href: columns.qmd
      - text: Subsetting rows (records)
        href: rows.qmd
      - text: Working with groups
        href: groups.qmd
      - text: Spatial
        href: spatial.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/BigelowLab/dataframes
          - text: Report a bug or ask a question
            url: https://github.com/BigelowLab/ColbyForecasting/dataframes
          - text: Tandy Center for Ocean Forecasting
            url: https://www.bigelow.org/science/centers/ocean-forecasting/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true

editor: source

